site_name: ExpressLRS
site_url: https://www.expresslrs.org/
site_author: ExpressLRS
site_description: >-
  ExpressLRS aims to provide the best completely open, high refresh radio
  control link while maintaining a maximum achievable range at that rate with
  low latency. Vast support of hardware in both 900 Mhz and 2.4 GHz frequencies.

# Repository
repo_name: ExpressLRS/ExpressLRS
repo_url: https://github.com/ExpressLRS/ExpressLRS/releases/
edit_uri: "https://github.com/ExpressLRS/Docs/tree/master/docs"

# Copyright
copyright: Copyright &copy; 2022 ExpressLRS

# Configuration
theme:
  name: material
  custom_dir: overrides

  # Static files
  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: expresslrs
      accent: expresslrs
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      default: expresslrs-dark
      primary: expresslrs-dark
      accent: expresslrs-dark
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/images/logotype.svg
  icon:
    logo: logo

plugins:
  - minify:
      minify_html: true

extra_css:
  - assets/stylesheets/main.css
  - assets/stylesheets/colors.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ExpressLRS/
      name: See the Github Repo
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dS6ReFY
      name: Check out the Discord
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/636441730280366
      name: Join the Facebook Group
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/expresslrs
      name: We're on Twitter too!
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/expresslrs
      name: Follow us on Instagram
    - icon: fontawesome/solid/donate
      link: https://opencollective.com/expresslrs
      name: Send a Donation!
  version:
    provider: mike
  generator: true

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ExpressLRS
      repo: ExpressLRS
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Quick Start:
      - Getting Started: quick-start/getting-started.md
      - Installing Configurator: quick-start/installing-configurator.md
      - Firmware Options: quick-start/firmware-options.md
      - Transmitters:
          - Preparing your Radio: quick-start/transmitters/tx-prep.md
          - Flashing Transmitters:
            - Axis Thor: quick-start/transmitters/axis-thor.md
            - BetaFPV 2.4GHz: quick-start/transmitters/betafpv2400.md
            - BetaFPV 900MHz: quick-start/transmitters/betafpv900.md
            - Frsky R9 Modules: quick-start/transmitters/frsky-r9modules.md
            - Happymodel ES24TX: quick-start/transmitters/es24tx.md
            - Happymodel ES900TX: quick-start/transmitters/es900tx.md
            - iFlight Commando: quick-start/transmitters/iflight-commando.md
            - IMRC Ghost: quick-start/transmitters/ghost2400.md
            - Internal RadioMaster: quick-start/transmitters/rm-internal.md
            - Internal Jumper T-Pro:  quick-start/transmitters/aion-internal.md
            - Jumper Aion Nano: quick-start/transmitters/jumper-aion.md
            - NamimnoRC Flash: quick-start/transmitters/flash2400.md
            - NamimnoRC Voyager: quick-start/transmitters/voyager900.md
            - Siyi FM30: quick-start/transmitters/siyifm30.md
            - Vantac Lite: quick-start/transmitters/vantac-lite.md
            - DIY 900TX: quick-start/transmitters/diy900.md
            - DIY 2400TX: quick-start/transmitters/diy2400.md
          - Using The Lua Script: quick-start/transmitters/lua-howto.md
      - Receivers:
          - Receiver Wiring: quick-start/receivers/wiring-up.md
          - Configuring FC: quick-start/receivers/configuring-fc.md
          - Flashing Receivers:
            - Axis Thor: quick-start/receivers/axis-thor.md
            - BetaFPV Lite & Nano 2.4GHz: quick-start/receivers/betafpv2400.md
            - BetaFPV Nano 900Mhz: quick-start/receivers/betafpv900.md
            - Frsky R9: quick-start/receivers/r9.md
            - GEPRC Nano 2.4GHz: quick-start/receivers/geprc2400.md
            - GEPRC Nano 900MHz: quick-start/receivers/geprc900.md
            - Happymodel EP: quick-start/receivers/hmep2400.md
            - Happymodel PP: quick-start/receivers/hmpp2400.md
            - Happymodel ES900RX: quick-start/receivers/hmes900.md
            - iFlight 2.4GHz: quick-start/receivers/iflight2400.md
            - iFlight 900MHz: quick-start/receivers/iflight900.md
            - IMRC Ghost: quick-start/receivers/ghost2400.md
            - Jumper Aion Nano: quick-start/receivers/jumper-aion.md
            - Jumper R9 Mini: quick-start/receivers/jumper900.md
            - Matek R24: quick-start/receivers/matek2400.md
            - NamimnoRC Flash: quick-start/receivers/flash2400.md
            - NamimnoRC Voyager: quick-start/receivers/voyager900.md
            - RadioMaster EP: quick-start/receivers/rmep2400.md
            - Siyi FR Mini: quick-start/receivers/siyiFRmini.md
            - Vantac: quick-start/receivers/vantac2400.md
            - DIY 900RX: quick-start/receivers/diy900.md
            - DIY 2400RX: quick-start/receivers/diy2400.md
      - Post-Flash:
        - LED Status: quick-start/led-status.md
        - Binding ExpressLRS: quick-start/binding.md
        - Pre-first Flight Checks: quick-start/pre-1stflight.md
        - Ardupilot Setup: quick-start/ardupilot-setup.md
      - Troubleshooting: quick-start/troubleshooting.md
      - Unbricking: quick-start/unbricking.md
  - Software:
      - Switch Configs: software/switch-config.md
      - User Defines: software/user-defines.md
      - Obsolete Defines: software/obsolete-defines.md
      - OpenOCD for STLink: software/open-ocd.md
      - Toolchain Setup: software/toolchain-install.md
      - PIO STLink Fix: software/stlink-fix.md
      - Updating:
        - Betaflight Passthrough: software/updating/betaflight-passthrough.md
        - Wifi Updating: software/updating/wifi-updating.md
      - Features:
        - Model Matching: software/model-config-match.md
        - Dynamic Transmit Power: software/dynamic-transmit-power.md
      - Testing:
        - CRC Testing: software/testing/crc-testing.md
        - Unit Testing: software/testing/unit-testing.md
        - RX Testing: software/testing/rx-scoreboard.md
  - Hardware:
      - Supported Hardware: hardware/supported-hardware.md
      - Receiver Selection: hardware/receiver-selection.md
      - R9M Inverter Mod: hardware/inverter-mod.md
      - R9M Fan Mod: hardware/fan-mod.md
      - Troubleshooting the X9D(+): hardware/x9d-troubleshooting.md
      - SMD Antenna: hardware/smd-antenna.md
      - PWM Receivers: hardware/pwm-receivers.md
      - SPI Receivers: hardware/spi-receivers.md
      - ESP Backpacks:
        - Backpack Info: hardware/backpack/esp-backpack.md
        - Tx Backpack Setup: hardware/backpack/backpack-tx-setup.md
        - VRx Backpack Setup: hardware/backpack/backpack-vrx-setup.md
      - Special Targets:
        - DIY Receiver: hardware/special-targets/diy-rx.md
        - DIY Transmitter: hardware/special-targets/diy-tx.md
        - Nuclear Targets: hardware/special-targets/nuclear-hardware.md
  - Info:
      - Glossary: info/glossary.md
      - Signal Health: info/signal-health.md
      - Telemetry Bandwidth: info/telem-bandwidth.md
      - Long Range Competition: info/long-range.md
      - Advance Technical Info: info/advance-technical-info.md
  - FAQ: faq.md
  - GSoD: gsod.md

extra_javascript:
  - assets/javascripts/binding-phrase.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - assets/javascripts/tablesort.js
