site_name: ExpressLRS
site_url: https://www.expresslrs.org/
site_author: ExpressLRS
site_description: >-
  ExpressLRS aims to provide the best completely open, high refresh radio
  control link while maintaining a maximum achievable range at that rate with
  low latency. Vast support of hardware in both 900 Mhz and 2.4 GHz frequencies.

# Repository
repo_name: ExpressLRS/ExpressLRS
repo_url: https://github.com/ExpressLRS/ExpressLRS/releases/
edit_uri: "https://github.com/ExpressLRS/Docs/tree/master/docs"

# Copyright
copyright: Copyright &copy; 2021 Team ExpressLRS

# Configuration
theme:
  name: material
  custom_dir: overrides

  # Static files
  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: expresslrs
      accent: expresslrs
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/images/logotype.svg
  icon:
    logo: logo

plugins:
  - search
  #  - redirects:
  - minify:
      minify_html: true
      

extra_css:
  - assets/stylesheets/main.css
  - assets/stylesheets/colors.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ExpressLRS/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dS6ReFY
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/636441730280366
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/expresslrs
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/expresslrs

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ExpressLRS
      repo: ExpressLRS
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Quick Start:
      - Getting Started: quick-start/getting-started.md
      - Installing Configurator: quick-start/installing-configurator.md
      - Firmware Options: quick-start/firmware-options.md
      - TX Modules:
          - Preparing your Radio: quick-start/tx-prep.md
          - Flashing TX Modules:
            - Flashing Frsky R9Ms: quick-start/tx-r9m.md
            - Flashing HM ES900TX: quick-start/tx-es900tx.md
            - Flashing NamimnoRC Voyager: quick-start/tx-voyager900.md
            - Flashing HM ES24TX: quick-start/tx-es24tx.md
            - Flashing NamimnoRC Flash: quick-start/tx-flash2400.md
            - Flashing Ghost TX: quick-start/tx-ghost2400.md
            - Flashing Siyi FM30: quick-start/tx-siyifm30.md
            - Flashing DIY 900TX: quick-start/tx-diy900.md
            - Flashing DIY 2400TX: quick-start/tx-diy.md
      - Receivers:
          - Flashing Bootloader: quick-start/rx-bootloader.md
          - Preparing for Passthrough Flashing: quick-start/rx-fcprep.md
          - Preparing for STLink Flashing: quick-start/rx-stlink.md
          - Flashing Receivers:
            - Flashing R9 Receivers: quick-start/rx-r9receivers.md
            - Flashing Jumper R9 Mini: quick-start/rx-jumper900.md
            - Flashing HM ES900RX: quick-start/rx-hmes900.md
            - Flashing NamimnoRC Voyager: quick-start/rx-voyager900.md
            - Flashing HM EP Receivers: quick-start/rx-hmep2400.md
            - Flashing HM PP Receiver: quick-start/rx-hmpp2400.md
            - Flashing NamimnoRC Flash: quick-start/rx-flash2400.md
            - Flashing Ghost Receiver: quick-start/rx-ghost2400.md
            - Flashing Siyi FR Mini: quick-start/rx-siyiFRmini.md
            - Flashing DIY 900RX: quick-start/rx-diyreceivers900.md
            - Flashing DIY 2400RX: quick-start/rx-diyreceivers.md
      - Post-Flash:
        - Binding ExpressLRS: quick-start/binding.md
        - Pre-first Flight Checks: quick-start/pre-1stflight.md
      - Troubleshooting: quick-start/troubleshooting.md
  - Software:
      - Switch Configs: software/switch-config.md
      - Obsolete Defines: software/obsolete-defines.md
      - OpenOCD for STLink: software/open-ocd.md
      - Toolchain Setup: software/toolchain-install.md
      - PIO STLink Fix: software/stlink-fix.md
      - Updating: 
        - Betaflight Passthrough: software/updating/betaflight-passthrough.md
        - Wifi Updating: software/updating/wifi-updating.md
  - Hardware:
      - Navigation Guide: hardware/supported-hardware.md
      - R9M Inverter Mod: hardware/inverter-mod.md
      - R9M Fan Mod: hardware/fan-mod.md
      - ESP Backpack: hardware/esp-backpack.md
      - SMD Antenna: hardware/smd-antenna.md
      - DIY Reciever: hardware/diy-rx.md
      - DIY Transmitter: hardware/diy-tx.md
  - Info:
      - Glossary: info/glossary.md
      - Signal Health: info/signal-health.md
      - Telemetry Bandwith: info/telem-bandwidth.md
  - FAQ: faq.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv [ "GOOGLE_ANALYTICS_KEY" ]
  - auto
