site_name: ExpressLRS
site_url: https://www.expresslrs.org/
site_author: ExpressLRS
site_description: >-
  ExpressLRS aims to provide the best completely open, high refresh radio
  control link while maintaining a maximum achievable range at that rate with
  low latency. Vast support of hardware in both 900 Mhz and 2.4 GHz frequencies.

# Repository
repo_name: ExpressLRS/ExpressLRS
repo_url: https://github.com/ExpressLRS/ExpressLRS/releases/
edit_uri: "https://github.com/ExpressLRS/Docs/tree/master/docs"

# Copyright
copyright: Copyright &copy; 2021 ExpressLRS

# Configuration
theme:
  name: material
  custom_dir: overrides

  # Static files
  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: expresslrs
      accent: expresslrs
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      default: expresslrs-dark
      primary: expresslrs-dark
      accent: expresslrs-dark
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/images/logotype.svg
  icon:
    logo: logo

plugins:
  - search
  #  - redirects:
  - minify:
      minify_html: true


extra_css:
  - assets/stylesheets/main.css
  - assets/stylesheets/colors.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ExpressLRS/
      name: See the Github Repo
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dS6ReFY
      name: Check out the Discord
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/636441730280366
      name: Join the Facebook Group
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/expresslrs
      name: We're on Twitter too!
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/expresslrs
      name: Follow us on Instagram
    - icon: fontawesome/brands/paypal
      link: https://www.paypal.com/donate?hosted_button_id=FLHGG9DAFYQZU
      name: Send a Donation!
  version:
    provider: mike
  generator: true

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ExpressLRS
      repo: ExpressLRS
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Quick Start:
      - Getting Started: quick-start/getting-started.md
      - Installing Configurator: quick-start/installing-configurator.md
      - Firmware Options: quick-start/firmware-options.md
      - TX Modules:
          - Preparing your Radio: quick-start/tx-prep.md
          - Flashing TX Modules:
            - Flashing Frsky R9 Modules: quick-start/tx-r9m.md
            - Flashing Happymodel ES900TX: quick-start/tx-es900tx.md
            - Flashing NamimnoRC Voyager: quick-start/tx-voyager900.md
            - Flashing BetaFPV Nano 900Mhz: quick-start/tx-betafpv900.md
            - Flashing Happymodel ES24TX: quick-start/tx-es24tx.md
            - Flashing NamimnoRC Flash: quick-start/tx-flash2400.md
            - Flashing BetaFPV Nano 2.4Ghz: quick-start/tx-betafpv2400.md
            - Flashing Ghost TX: quick-start/tx-ghost2400.md
            - Flashing Siyi FM30: quick-start/tx-siyifm30.md
            - Flashing DIY 900TX: quick-start/tx-diy900.md
            - Flashing DIY 2400TX: quick-start/tx-diy.md
      - Receivers:
          - Flashing Bootloader: quick-start/rx-bootloader.md
          - Preparing for Passthrough Flashing: quick-start/rx-fcprep.md
          - Preparing for STLink Flashing: quick-start/rx-stlink.md
          - Flashing Receivers:
            - Flashing Frsky R9 Receivers: quick-start/rx-r9receivers.md
            - Flashing Jumper R9 Mini: quick-start/rx-jumper900.md
            - Flashing Happymodel ES900RX: quick-start/rx-hmes900.md
            - Flashing NamimnoRC Voyager: quick-start/rx-voyager900.md
            - Flashing BetaFPV Nano 900Mhz: quick-start/rx-betafpv900.md
            - Flashing Happymodel EPs: quick-start/rx-hmep2400.md
            - Flashing Happymodel PP: quick-start/rx-hmpp2400.md
            - Flashing NamimnoRC Flash: quick-start/rx-flash2400.md
            - Flashing BetaFPV Nano 2.4G: quick-start/rx-betafpv2400.md
            - Flashing Matek R24: quick-start/rx-matek2400.md
            - Flashing Ghost Receiver: quick-start/rx-ghost2400.md
            - Flashing Siyi FR Mini: quick-start/rx-siyiFRmini.md
            - Flashing DIY 900RX: quick-start/rx-diyreceivers900.md
            - Flashing DIY 2400RX: quick-start/rx-diyreceivers.md
      - Post-Flash:
        - Binding ExpressLRS: quick-start/binding.md
        - Pre-first Flight Checks: quick-start/pre-1stflight.md
        - Ardupilot Setup: quick-start/ardupilot-setup.md
      - Troubleshooting: quick-start/troubleshooting.md
  - Software:
      - Switch Configs: software/switch-config.md
      - User Defines: software/user-defines.md
      - Obsolete Defines: software/obsolete-defines.md
      - OpenOCD for STLink: software/open-ocd.md
      - Toolchain Setup: software/toolchain-install.md
      - PIO STLink Fix: software/stlink-fix.md
      - Updating:
        - Betaflight Passthrough: software/updating/betaflight-passthrough.md
        - Wifi Updating: software/updating/wifi-updating.md
  - Hardware:
      - Supported Hardware: hardware/supported-hardware.md
      - R9M Inverter Mod: hardware/inverter-mod.md
      - R9M Fan Mod: hardware/fan-mod.md
      - Troubleshooting the X9D(+): hardware/x9d-troubleshooting.md
      - ESP Backpack: hardware/esp-backpack.md
      - SMD Antenna: hardware/smd-antenna.md
      - SPI Receivers: hardware/spi-receivers.md
      - Special Targets:
        - DIY Receiver: hardware/diy-rx.md
        - DIY Transmitter: hardware/diy-tx.md
        - Nuclear Targets: hardware/nuclear-hardware.md
  - Info:
      - Glossary: info/glossary.md
      - Signal Health: info/signal-health.md
      - Telemetry Bandwith: info/telem-bandwidth.md
      - Testing:
        - Unit Testing: info/unit-testing.md
        - CRC Testing: info/crc-testing.md
        - RX Scoreboard: info/rx-scoreboard.md
  - FAQ: faq.md

extra_javascript:
  - assets/javascripts/binding-phrase.js
